export const USER_BOOKS_REQUEST = 'USER_BOOKS_REQUEST'
export const USER_BOOKS_SUCCESS = 'USER_BOOKS_SUCCESS'
export const USER_BOOKS_FAIL = 'USER_BOOKS_SUCCESS'
export const USER_BOOKS_DELETE = 'USER_BOOKS_DELETE'
export const USER_BOOKS_UPDATE = 'USER_BOOKS_UPDATE'


export const USER_LIKES_SUCCESS = 'USER_LIKES_SUCCESS'
export const USER_LIKES_REQUEST = 'USER_DETAILS_SUCCESS'
export const USER_LIKES_FAIL = 'USER_DETAILS_FAIL'
export const USER_LIKES_DELETE = 'USER_DETAILS_RESET'
export const USER_LIKES_UPDATE = 'USER_LIKES_UPDATE'

export const USER_FOLLOW_SUCCESS = 'USER_FOLLOW_SUCCESS'
export const USER_FOLLOW_REQUEST = 'USER_FOLLOW_REQUEST'
export const USER_FOLLOW_FAIL = 'USER_FOLLOW_FAIL'
export const USER_FOLLOW_DELETE = 'USER_FOLLOW_DELETE'
export const USER_FOLLOW_UPDATE = 'USER_FOLLOW_UPDATE'